version: "3.9"
name: nextjs-upload
services:
  web:
    image: vinhintw2014/nextjs-upload:latest
    container_name: nextjs-upload
    ports:
      - 18001:3000
    volumes:
      - ./:/app
    env_file:
      - .env
