version: "3.9"
name: nextjs-upload
services:
  web:
    container_name: nextjs
    build:
      context: ../
      dockerfile: compose/web.Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    ports:
      - 3000:3000
    environment:
      - ../.env
    volumes:
      - ../:/app
    command: sh ./compose/db-push-and-start.sh
  
